/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Paper / archive system (light, document-toned) ──
        // Legacy Material token names are remapped to paper values so
        // token-based components re-theme without edits.
        "surface-variant": "#C7B99C",
        "on-secondary-container": "#1E4E8C",
        "surface-container": "#DDD2B6",
        "on-error": "#E9E0CC",
        "tertiary": "#514739",
        "on-surface": "#211C15",
        "secondary-container": "#1E4E8C",
        "on-primary": "#E9E0CC",
        "surface-container-lowest": "#D2C6A8",
        "surface-tint": "#1E4E8C",
        "error-container": "#A23A28",
        "on-primary-fixed-variant": "#1E4E8C",
        "inverse-surface": "#211C15",
        "on-secondary": "#E9E0CC",
        "surface": "#E9E0CC",
        "on-tertiary": "#E9E0CC",
        "primary": "#1E4E8C",
        "outline": "#C7B99C",
        "inverse-primary": "#1E4E8C",
        "on-secondary-fixed-variant": "#1E4E8C",
        "primary-fixed-dim": "#1E4E8C",
        "background": "#E9E0CC",
        "primary-fixed": "#1E4E8C",
        "on-error-container": "#A23A28",
        "primary-container": "#211C15",
        "on-tertiary-fixed-variant": "#514739",
        "outline-variant": "#C7B99C",
        "tertiary-container": "#3E7D5A",
        "inverse-on-surface": "#E9E0CC",
        "surface-container-high": "#C7B99C",
        "surface-bright": "#E9E0CC",
        "on-tertiary-fixed": "#E9E0CC",
        "secondary": "#1E4E8C",
        "on-surface-variant": "#514739",
        "on-background": "#211C15",
        "on-primary-fixed": "#E9E0CC",
        "tertiary-fixed-dim": "#514739",
        "secondary-fixed": "#1E4E8C",
        "on-secondary-fixed": "#E9E0CC",
        "on-tertiary-container": "#E9E0CC",
        "surface-container-highest": "#C7B99C",
        "error": "#A23A28",
        "tertiary-fixed": "#514739",
        "surface-container-low": "#DDD2B6",
        "surface-dim": "#E9E0CC",
        "on-primary-container": "#E9E0CC",
        "secondary-fixed-dim": "#1E4E8C",

        // ── Named paper tokens used by the redesigned views ──
        "paper": "#E9E0CC",
        "paper-deep": "#DDD2B6",
        "ink": "#211C15",
        "ink-soft": "#514739",
        "rule": "#C7B99C",
        "cite": "#1E4E8C",
        "pass": "#3E7D5A",
        "warn": "#A23A28",
      },
      spacing: {
        "container-max": "1440px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "margin": "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Space Grotesk", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
        serif: ["Spectral", "serif"],
        "inter": ["Space Grotesk", "sans-serif"],
        "geist": ["IBM Plex Mono", "monospace"],
        "jetbrains": ["IBM Plex Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-block": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out",
      },
      boxShadow: {
        "card": "0 1px 2px rgba(33, 28, 21, 0.08)",
        "card-hover": "0 2px 6px rgba(33, 28, 21, 0.12)",
      },
    },
  },
  plugins: [],
};
