/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Desktop / Dark palette (charcoal-dark)
        "surface-variant": "#303443",
        "on-secondary-container": "#004964",
        "surface-container": "#1a1f2d",
        "on-error": "#690005",
        "tertiary": "#bdc6e2",
        "on-surface": "#dee2f5",
        "secondary-container": "#00bdfd",
        "on-primary": "#581e00",
        "surface-container-lowest": "#090e1b",
        "surface-tint": "#ffb596",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#7c2e00",
        "inverse-surface": "#dee2f5",
        "on-secondary": "#003549",
        "surface": "#0e1320",
        "on-tertiary": "#273046",
        "primary": "#ffb596",
        "outline": "#aa8a7d",
        "inverse-primary": "#a33e00",
        "on-secondary-fixed-variant": "#004c69",
        "primary-fixed-dim": "#ffb596",
        "background": "#0e1320",
        "primary-fixed": "#ffdbcd",
        "on-error-container": "#ffdad6",
        "primary-container": "#ff6600",
        "on-tertiary-fixed-variant": "#3e465d",
        "outline-variant": "#5a4136",
        "tertiary-container": "#8d96b0",
        "inverse-on-surface": "#2b303e",
        "surface-container-high": "#252a38",
        "surface-bright": "#343948",
        "on-tertiary-fixed": "#121b30",
        "secondary": "#8bd5ff",
        "on-surface-variant": "#e3bfb1",
        "on-background": "#dee2f5",
        "on-primary-fixed": "#360f00",
        "tertiary-fixed-dim": "#bdc6e2",
        "secondary-fixed": "#c3e8ff",
        "on-secondary-fixed": "#001e2c",
        "on-tertiary-container": "#262f44",
        "surface-container-highest": "#303443",
        "error": "#ffb4ab",
        "tertiary-fixed": "#d9e2fe",
        "surface-container-low": "#161b29",
        "surface-dim": "#0e1320",
        "on-primary-container": "#561d00",
        "secondary-fixed-dim": "#7ad0ff",
        // Mobile accent: green tertiary
        "mobile-tertiary": "#4ae176",
        "mobile-tertiary-container": "#00ae4f",
        "mobile-surface": "#001231",
        "mobile-background": "#001231",
        "mobile-surface-container": "#001e48",
        "mobile-surface-high": "#02285b",
        "mobile-surface-highest": "#133466",
        "mobile-surface-variant": "#133466",
        "mobile-surface-bright": "#18386b",
        "mobile-surface-lowest": "#000d27",
      },
      spacing: {
        "container-max": "1440px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "margin": "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "Geist", "monospace"],
        "inter": ["Inter", "sans-serif"],
        "geist": ["Geist", "monospace"],
        "jetbrains": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-block": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      keyframes: {
        sweep: {
          "0%": { opacity: "0", marginTop: "-10px" },
          "100%": { opacity: "1", marginTop: "0px" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        sweep: "sweep 0.3s ease-in-out",
        "fade-in": "fade-in 0.3s ease-out",
      },
    },
  },
  plugins: [],
};
